### ISSUE TITLE
bleu error

### ISSUE THREAD

**Issue by b10112157** [salaniz/pycocoevalcap#1]
i use captions_val2014.json，but bleu value wrong .  how to solve it.?

**gts = tokenizer.tokenize(gts)**
i try "**print (gts)** in eval.py",but show the **{458755: ['']}**
my equip is py 3.5.4,and tf 1.4.0
![image](https://user-images.githubusercontent.com/31722850/40662411-dc50cece-6388-11e8-8f24-51f410272e33.png)

**Comment by salaniz** [comment]
Can you please try to run the example from the original repository https://github.com/tylin/coco-caption, namely by getting:
- annotations/captions_val2014.json
- results/captions_val2014_fakecap_results.json
and then running the provided notebook: cocoEvalCapDemo.ipynb
Does the code work then? Maybe your results.json is not in the correct format?

**Comment by b10112157** [comment]
i can run this  https://github.com/tylin/coco-caption,  project ,and ****can get  Meaningful bleu value.**** 
but i use the annotations/captions_val2014.json and results/captions_val2014_fakecap_results.json for my project **can not   get  Meaningful bleu value.**

or can u test for mine .json pls 
1. my result.json https://drive.google.com/file/d/1DIFoQdOiM8oayqvvKq0WZpd9pOOSTTAx/view?usp=sharing[](urlhttps://drive.google.com/file/d/1DIFoQdOiM8oayqvvKq0WZpd9pOOSTTAx/view?usp=sharing)

**Comment by salaniz** [comment]
You have to use the current project for Python 3 support not the original one.

So you have to do the following on a clean directory:
- clone and install https://github.com/cocodataset/cocoapi (find the instructions in the readme and make sure you can run 'import pycocotools' afterwards)
- clone this repository (https://github.com/salaniz/pycocoevalcap), you should be able to run 'import pycocoevalcap' now
- copy the files annotations/captions_val2014.json and results/captions_val2014_fakecap_results.json from https://github.com/tylin/coco-caption (do not clone the whole repository)
- from the same directory, see if you can run this code:

```python
from pycocotools.coco import COCO
from pycocoevalcap.eval import COCOEvalCap

dataDir = '.'
dataType = 'val2014'
algName = 'fakecap'
annFile = '%s/annotations/captions_%s.json'%(dataDir,dataType)
resFile = '%s/results/captions_%s_%s_results.json'%(dataDir,dataType,algName)

coco = COCO(annFile)
cocoRes = coco.loadRes(resFile)

cocoEval = COCOEvalCap(coco, cocoRes)
cocoEval.params['image_id'] = cocoRes.getImgIds()

cocoEval.evaluate()
```

**Comment by b10112157** [comment]
in the step 1:
command line in **cocoapi/pythonAPI** **"python setup.py build_ext --inplace"** and **"python setup.py build_ext install"**
Is it the correct procedure? but show output that 
![image](https://user-images.githubusercontent.com/31722850/40727932-9955cac4-645b-11e8-9a58-fb16dd238e0a.png)

**Comment by salaniz** [comment]
I seems like you don’t have a C++ compiler installed or it's not in your PATH environment variable because the error comes from not finding cl.exe.

**Comment by b10112157** [comment]
now it can "import pycocotools " 
in the step 2, i put the bleu

**Comment by salaniz** [comment]
Then I assume the issue is resolved.
