### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Guardian-in-the-WF** [salaniz/pycocoevalcap#19]
File "/home/amax/Documents/YBK/Image_to_text/54_Dynamic_graph/code/DCL-main/generation_api/pycocoevalcap/meteor/meteor.py", line 63, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
BrokenPipeError: [Errno 32] Broken pipe

excuse me, how can i solve the problem about BrokenPipeError? Could you give me some hints?

**Comment by salaniz** [comment]
Sorry for getting back only now, but there is not enough information here for me to reproduce the error.
I am closing now, but feel free to provide more information if this is still a problem.
