### ISSUE TITLE
meteor.py

### ISSUE THREAD

**Issue by gorgeousyouth** [salaniz/pycocoevalcap#3]
excuse me, do you modify the  spice.py?

**Comment by gorgeousyouth** [comment]
would you mind telling me the reason about this?

**Comment by salaniz** [comment]
It seems like spice was added to the original repository after I made my changes. Do you mean to say that you would like to have it included in this repository?

**Comment by gorgeousyouth** [comment]
> It seems like spice was added to the original repository after I made my changes. Do you mean to say that you would like to have it included in this repository?

yeah, I can not use the  original repository spice  because of the java version. My java version is 1.7.
Best,

**Comment by salaniz** [comment]
If I include spice, it will be the same as in the original repository. So most likely you will need Java 1.8 to run it either way. This repository only changes the Python code so you can use Python 3.

**Comment by gorgeousyouth** [comment]
> If I include spice, it will be the same as in the original repository. So most likely you will need Java 1.8 to run it either way. This repository only changes the Python code so you can use Python 3.

Thanks
