### ISSUE TITLE
is your code guaranteed?

### ISSUE THREAD

**Issue by fawazsammani** [salaniz/pycocoevalcap#4]
Hi, and thanks for the code!
I'd like to know if your code performs exactly the same as the original one. I am using your code in my research work on Image Captioning, and the results I got are exceptional (they are higher than any state-of-art). So it's either my architecture is so good, or your code has a different performance. Please understand that if the results I demonstrate in the paper happen to be incorrect, I will be in big trouble. So may I know if the code is 100% same as the original?

Thanks and Regards

**Comment by salaniz** [comment]
You can easily verify (i.e. look through) the changes this repository introduces in the few commits I made in this repository. They only resolve around replacing Python 2 functions with equivalent functions from Python 3.

I am confident that these changes do not alter the underlying algorithms, but I encourage you to make independent tests if you have doubts.

Please note that there is no liability from the authors of the code including myself as stated in the project's license (equivalent to the one from the original repository).
